### ISSUE TITLE
Panic when quiting the CLI

### ISSUE THREAD

**Issue by jbarnoud** [IRL2/nanover-rs#180]
When quitting the CLI with ctr+c, the following panic occurs:

> thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', narupa-rs/src/simulation_thread.rs:59:48

**Comment by Ragzouken** [comment]
I got this when (unrelated) the headset crashed while connecting to the server. Not sure if it's relevant but before that I was start/stopping the server rapidly with the neurominidase simulation.

> thread 'tokio-runtime-worker' panicked at nanover-rs\src\simulation_thread.rs:132:48:
called `Result::unwrap()` on an `Err` value: SendError { .. }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at nanover-rs\src\simulation_thread.rs:132:48:
called `Result::unwrap()` on an `Err` value: SendError { .. }
thread 'tokio-runtime-worker' panicked at nanover-rs\src\simulation_thread.rs:132:48:
called `Result::unwrap()` on an `Err` value: SendError { .. }
thread 'tokio-runtime-worker' panicked at nanover-rs\src\simulation_thread.rs:132:48:
called `Result::unwrap()` on an `Err` value: SendError { .. }
thread 'tokio-runtime-worker' panicked at nanover-rs\src\simulation_thread.rs:132:48:
called `Result::unwrap()` on an `Err` value: SendError { .. }
